--- 
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nginx-app
        namespace: default
      spec:
         replicas: 1
         selector:
            matchLabels:
               app: web
         template:
            metadata:
               labels:
                  app: web
            spec:
               containers:
                  - name: nginx-checkmarx
                    image: "elchananmizrachi/checkmark:latest"
                    ports:
                       - containerPort: 80
